---
title: "Macular Degeneration"
author: "Cooper Riggs, Adam Bitner, & Stockton Nelson"
format: pdf
editor: visual
---

## Setup

```{r}
#Downloading Libraries
library(tidyverse)

#Bringing in Data
eyes <- vroom::vroom("ARMD.txt") |>
  janitor::clean_names() |>
  mutate(treatment = as.factor(trt)) |>
  select(-trt)
```

## Problem 1 (Stockton)

### EDA

```{r}
#Making a Violin Plot
ggplot(eyes, aes(x = vision, y = as.factor(time), fill = treatment, color = treatment)) +
  geom_violin(draw_quantiles = c(0.25, 0.5, 0.75)) +
  scale_fill_manual(values = c("0" = "#032C3C",   
                                 "1" = "#BA351A"),
               labels = c("Placebo", expression(paste("Interferon ", alpha)))) +
  scale_color_manual(
    values = c("0" = "#8B9092", "1" = "black")  # Outline and quantiles by treatment
  ) +
  labs(x = "Vision Score",
       y = "Week",
       fill = "Treatment") +
  theme(
    panel.background = element_rect(fill = "#F5F5F5"),
    plot.background = element_rect(fill = "#EAEAEA"),
    panel.grid.major = element_line(color = "white"),
    legend.background = element_rect(fill = "#EAEAEA", color = "black"),
    legend.position = "none"
  )

#Saving the Violin Plot
# ggsave("Violin_Plot.png", width = 10, height = 6, dpi = 300)
```

```{r}
#Creating Time Series Plot
ggplot(data = eyes, aes(x = time, y = vision, color = treatment)) +
  stat_summary(fun = mean, geom = "line") +
  stat_summary(fun = mean, geom = "point") +
  scale_color_manual(values = c("0" = "#032C3C",   
                                 "1" = "#BA351A"),
               labels = c("Placebo", expression(paste("Interferon ", alpha)))) +
  labs(x = "Week",
       y = "Vision Score",
       color = "Treatment") + #,
       #title = "Time Series of Vision Scores",
       #subtitle = "Comparing Vision Scores between Treatment Types") +
  theme(
    panel.background = element_rect(fill = "#F5F5F5"),
    plot.background = element_rect(fill = "#EAEAEA"),
    panel.grid.major = element_line(color = "white"),
    legend.background = element_rect(fill = "#EAEAEA", color = "black"),
    legend.position = "none"
  )

#Saving the Time Series
# ggsave("Time_Series.png", width = 10, height = 6, dpi = 300)
```

## Problem 2 (Adam)

### Modeling

```{r}
library(nlme)
library(tidyr)
# linear model and seeing correlation
mod <- lm(vision ~ time + treatment + baseline + time:baseline + time:treatment + treatment:baseline, data = eyes)

eyes$resid <- residuals(mod)
resid_wide <- eyes %>%
  select(subject, time, resid) %>%
  pivot_wider(
    names_from = time,
    values_from = resid
  )

resid_matrix <- as.matrix(resid_wide[,-1])
cor(resid_matrix, use = "complete.obs")
```

```{r}
# gls model
my_model <- gls(vision ~ time + treatment + baseline + time:baseline + time:treatment + treatment:baseline, data=eyes, correlation=corSymm(form=~4|subject))
my_model$modelStruct$corStruct
sigma(my_model)
coef(my_model)
```

## Problem 3 (Cooper)

### Inference

```{r}
library(multcomp)

glht_test <- glht(my_model, linfct = c("time:treatment1 = 0"))
summary(glht_test)
```

```{r}
confint(glht_test)
```

## Problem 4 (Cooper)

### Prediction

```{r}
new_data <- data.frame(
  time = 52,
  treatment = factor(c(0,1)),
  baseline = mean(eyes$baseline)
)
predict(my_model, newdata = new_data)
```
